stages:
  - build

variables:
  JAVA_HOME: "/usr/lib/jvm/java-21-openjdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

build:
  stage: build
  image: gradle:latest
  before_script:
    - apt-get update -y
    - apt-get install -y openjdk-21-jdk
    - export JAVA_HOME
  script:
    - gradle --version
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - main

