stages:
  - test
  - build
  # - release

test:
  stage: test
  image: gradle:latest
  only:
    - main
  before_script:
    - gradle --version
  script:
    - ./gradlew test

build:
  stage: build
  image: gradle:latest
  only:
    - main
  before_script:
    - gradle --version
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

# release:
#   stage: release
#   only:
#     - main
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind
#   before_script:
#     - docker info
#   script:
#     - docker build -t ms-auth-java-app .
#     # - docker tag ms-auth-java-app <url>
#     # - docker push <url>
