spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:ms_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  liquibase:
    change-log: classpath:db.changelog/db.changelog.yaml
    enabled: true
    drop-first: false
    database-change-log-table: change_log
    database-change-log-lock-table: change_log_lock

server:
  port: 8080


application:
  security:
    secret-key: c2VjdXJlLXNlY3JldC1rZXktZm9yLUpXVC1lbmNyeXB0aW9uLTMyYnl0ZXM=
    jwt:
      expiration: 900000
      refresh-token:
        expiration: 86400000
